org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#-----------------------------

mod_id=immersivepetroleum
mod_version=4.4.1-37
mod_group=flaxbeard.immersivepetroleum

#-----------------------------

version_minecraft=1.21.1
version_neo=21.1.164
version_parchment=2024.11.17
version_mdg=2.0.30-beta

version_ie=1.21.1-12.4.2-194
version_jei=19.10.0.126
version_dualcodecs=0.1.2

version_ct=14.0.38
version_cctweaked=1.110.2
