modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]]
	modId="immersivepetroleum"
	version="${ip_version}"
	displayName="Immersive Petroleum"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum"
	authors="Flaxbeard and Maintained by TwistedGate."
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	type="required"
	versionRange="[${ie_version},)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="neoforge"
	type="required"
	versionRange="[${neo_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	type="required"
	versionRange="[${mc_version}]"
	ordering="NONE"
	side="BOTH"
